export {
    getData, getInfo,
    FETCH_POKEMON_DATA_START,
    FETCH_POKEMON_DATA_SUCCESS,
    FETCH_POKEMON_DATA_FAILURE,
    FETCH_POKEMON_INFO_DATA_START,
    FETCH_POKEMON_INFO_DATA_SUCCESS,
    FETCH_POKEMON_INFO_DATA_FAILURE,
} from './pokemonActions';

export {
    getSets,
    FETCH_SETS_DATA_START,
    FETCH_SETS_DATA_SUCCESS,
    FETCH_SETS_DATA_FAILURE
} from './setsActions';
